language: rust
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - gfortran
rust:
  - 1.32.0
  - stable
install:
  - rustup component add clippy
  - rustup component add rustfmt
script: ci/script.sh